# Create_Initial_Model.py
import os
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, BatchNormalization
from tcn import TCN

# --- Configuration ---
NUM_CLASSES = 9
SHAPE_PATH = "Data_Schema/model_input_shape.txt"
OUTPUT_DIR = "DL_Global_Deployment_Initial"

# Optional GPU optimization
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

def create_tcn_gru_model(input_shape, num_classes, learning_rate=0.001):
    """
    [Architecture Upgrade] Deep Fully Connected Network (DNN) optimized for 47-dimensional tabular data.
    Although the function name 'tcn_gru' is retained for backward compatibility, 
    the kernel has been upgraded to an MLP better suited for the current data.
    """
    from tensorflow.keras.layers import Flatten
    
    model = Sequential([
        # 1. Flatten the input (as the input shape might be (1, 47))
        Flatten(input_shape=input_shape),
        
        # 2. First layer with wide neurons to fully extract non-linear features
        Dense(256, activation='relu'),
        BatchNormalization(),
        Dropout(0.3),
        
        # 3. Second layer for gradual dimensionality reduction
        Dense(128, activation='relu'),
        BatchNormalization(),
        Dropout(0.3),
        
        # 4. Third layer for feature refinement
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),

        # Added new layer
        Dense(64, activation='relu'),
        BatchNormalization(),
        
        # 5. Output layer
        Dense(num_classes, activation='softmax')
    ])
    
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

def main():
    print(f"{'='*60}")
    print("   Initializing Global HFL Model (TON_IoT Architecture)")
    print(f"{'='*60}")
    
    # 1. Read the input shape generated by DataUtils_Client.py
    if not os.path.exists(SHAPE_PATH):
        print(f"\n[FATAL ERROR] Shape file not found at '{SHAPE_PATH}'.")
        print("Please run a data processing script with 'is_creator=True' first to generate the schema.")
        return
        
    with open(SHAPE_PATH, "r") as f:
        dims = f.read().split(',')
        input_shape = (int(dims[0]), int(dims[1]))
        
    print(f"   -> Detected Input Shape: {input_shape} (Timesteps, Features)")
    print(f"   -> Configured for {NUM_CLASSES} Classes.")
    
    # 2. Build the Model
    model = create_tcn_gru_model(input_shape, num_classes=NUM_CLASSES)
    model.summary()
    
    # 3. Save the Initial Weights
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    output_path = os.path.join(OUTPUT_DIR, "initial_global_model.weights.h5")
    
    model.save_weights(output_path)
    print(f"\n[SUCCESS] Initial Global Model weights saved to:\n{output_path}")

if __name__ == "__main__":
    main()